config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users, controllers: {sessions: "sessions", registrations: "custom_registrations"}
  root to: 'pages#home'
  get "/ref=producthunt" => "pages#home"
  get "/payment" => "pages#payment", as: 'payment'
  post "/create-checkout-session" => "payments#redirect_stripe"
  # post '/hooks/stripe' => 'payments#receive'
  post '/webhook_events/:source', to: 'webhook_events#create'
  devise_scope :user do
    get "meet_bot", to: "telegram_set_up#meet_bot"
    get "shake_hands", to: "telegram_set_up#shake_hands"
    get "add_first_resource", to: "telegram_set_up#add_first_resource"
    get "/telegram_set_up/stat_telegram_chat_id", to: "telegram_set_up#stat_telegram_chat_id"
    get "/telegram_set_up/stat_added_first_item", to: "telegram_set_up#stat_added_first_item"
    get "/telegram_set_up/current_shelf", to: "telegram_set_up#current_shelf"
    get "sessions/extension", to: "sessions#new_ext"
    post "sessions/extension", to: "sessions#create_ext"
    get "/sessions/start_extension", to: "sessions#start_extension"
  end
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :items, only: [ :index, :create ]
    end
  end
  resources :telegram_set_up, only: [:new, :create] do
    collection do
      get 'stat_telegram_chat_id'
      get 'stat_added_first_item'
      get 'current_shelf'
    end
  end
  resources :shelves, only: [:new, :create, :show], param: :username do
    member do
      get 'shelf_children'
    end
  end
  resources :spaces do
    collection do
      post :move_space_to_space
      post :move_space_to_shelf
    end
    member do
      patch :move
      get 'space_name'
      get 'space_children'
    end
  end
  resources :items do
    collection do
      post :move_to_space
      post :move_to_shelf
      post :persist_mp3_url
      post :persist_audio_timestamp
      post :persist_audio_duration
      post :mark_as_finished
      get 'item_audio_duration'
      get 'was_item_added'
    end
    member do
      patch :move
    end
  end
  post '/application/update_balance_temp', to: 'application#update_balance_temp'
  post '/application/update_balance_final', to: 'application#update_balance_final'
  post '/application/pay_back_balance', to: 'application#pay_back_balance'
  get '/application/user_balance', to: 'application#user_balance'
end

app/models/space.rb
class Space < ApplicationRecord
  #acts_as_list
  has_and_belongs_to_many :shelves
  has_and_belongs_to_many :items
  has_many :connections, dependent: :destroy
  has_many :children, through: :connections

  before_create :set_position

  def set_position
    self.position = 1 if position.blank?
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
skip_before_action :authenticate_user!, :only => [:show, :create, :destroy, :move_space_to_space, :move_space_to_shelf, :space_name, :space_children]
before_action :set_space, only: [:show, :edit, :update, :destroy, :move]
before_action :set_shelf, only: [:create, :add_item_to, :show, :destroy, :move_space_to_space, :move_space_to_shelf, :move]
skip_after_action :verify_authorized, only: [:space_name, :space_children]
skip_before_action :verify_authenticity_token # vulnerability?

  def new
    if params[:shelf_id].present?
      @space = Space.new
      authorize @space
      @shelf = Shelf.find(params[:shelf_id])
    elsif params[:parent_id].present?
      @parent = Space.find(params[:parent_id])
      @child = Space.new
      authorize @child
    end
  end

  def create
    if params[:space][:shelf_id].present?
      @space = Space.new(space_params)
      authorize @space
      @space.save
      @shelf = Shelf.find(params[:space][:shelf_id])
      @shelf.items.update_all('position = position + 1') # every new object has position 1 by default --> pushes all other positions to the right
      @shelf.spaces.update_all('position = position + 1')
      @shelf.spaces << @space
      if params[:space][:item_id]
        add_item_to(@space)
        redirect_to space_path(@space)
      elsif params[:space][:space_id]
        # space est déjà créé dans shelf. il faut juste ajouter le space child dans space.
        # trouver child
        @child = Space.find(params[:space][:space_id])
        # trouver sa position
        child_position = @child.position
        @child.connections.each do |connection|
          if connection.parent_id.nil? == false
            @initial_space = connection.parent.space
          end
        end
        # si child est dans un space initial_space
        if @child.shelves.empty?
          # créer nvelle connection de child à space
          s1 = Connection.create(space: @space)
          co = s1.children.create(space: @child)
          # si child a des enfants
          if @child.children.empty? == false
            # rediriger toutes les co avec les enfants de child vers cette nvelle co
            @child.children.each do |connection|
              connection.parent_id = co.id
              connection.save
            end
          end
          # supprimer la co de child à initial_space
          @child.connections.each do |connection|
            if (connection.parent.nil? == false) && (connection.parent.space == @initial_space)
              connection.destroy
            end
          end
          # mettre -1 à ts les objets et spaces après child dans initial_space
          @initial_space.items.where('position > ?', child_position).update_all('position = position - 1')
          @initial_space.children.each do |connection|
            if connection.space.position > child_position
              connection.space.position = connection.space.position - 1
              connection.space.save
            end
          end
        # si child est sur la shelf // ca n'a pas trop de sens de le mettre dans un nv space sur la shelf...
        else
          # rompre co avec la shelf
          @child.shelves.destroy_all
          # créer la connection à space
          s1 = Connection.create(space: @space)
          co = s1.children.create(space: @child)
          # mettre -1 à ts les éléments après lui sur la shelf
          @shelf.items.where('position > ?', grand_child_position).update_all('position = position - 1') # every new object has position 1 by default --> pushes all other positions to the right
          @shelf.spaces.where('position > ?', grand_child_position).update_all('position = position - 1')
          # vérif que ca tient s'il a des enfants
        end
        redirect_to space_path(@space)
      else
        redirect_to shelf_path(@shelf.username)
      end
      if current_user != User.first
        UserNotifierMailer.inform_louis_of_new_space(@space, shelf_mother_of_space(@space).user).deliver
      end
    elsif params[:space][:parent_id].present?
      @child = Space.new(space_params)
      authorize @child, policy_class: SpacePolicy
      @child.save
      @parent = Space.find(params[:space][:parent_id])
      @parent.items.update_all('position = position + 1')
      @parent.children.each do |connection|
        connection.space.position += 1
        connection.space.save
      end
      if !@parent.shelves.empty? && @parent.connections.empty?
        s1 = Connection.create(space: @parent)
        s2 = s1.children.create(space: @child)
      else
        s2 = @parent.connections.first.children.create(space: @child)
      end
      if params[:space][:item_id]
        add_item_to(@child)
        redirect_to space_path(@child)
      elsif params[:space][:space_id]
        # child (nouveau space créé) est déjà dans parent. goal: mettre grand_child dans child
        # trouver grand_child
        @grand_child = Space.find(params[:space][:space_id])
        # trouver sa position
        grand_child_position = @grand_child.position
        # si grand_child est sur la shelf
        if @grand_child.shelves.empty? == false
          # copier code pr trouver la shelf, mettre -1 à ts les objets et spaces, détruire co
          @shelf.items.where('position > ?', grand_child_position).update_all('position = position - 1') # every new object has position 1 by default --> pushes all other positions to the right
          @shelf.spaces.where('position > ?', grand_child_position).update_all('position = position - 1')
          @grand_child.shelves.destroy_all
          if !@child.shelves.empty? && @child.connections.empty? # si un space est sur une shelf, et n'est pas encore parent (i.e. n'a aucune connection)
            s1 = Connection.create(space: @child)
            s1.children.create(space: @grand_child)
          else
            @child.connections.first.children.create(space: @grand_child)
          end
        # si grand_child est dans un space: initial_space
        else # elsif...)
          # trouver ce space initial_space
          @grand_child.connections.each do |connection|
            if connection.parent_id.nil? == false
              @initial_space = connection.parent.space
            end
          end
          # mettre -1 à ts les objets et spaces dans @initial_space
          @initial_space.items.where('position > ?', grand_child_position).update_all('position = position - 1')
          @initial_space.children.each do |connection|
            if connection.space.position > grand_child_position
              connection.space.position = connection.space.position - 1
              connection.space.save
            end
          end
          # si grand child has children
          if @grand_child.children.empty? == false
            # d'abord créer la co de grand child à child
            parent_connection = nil
            @child.connections.each do |connection|
              if connection.parent_id == nil
                parent_connection = connection
              end
            end
            if parent_connection
              co = parent_connection.children.create(space: @grand_child)
            else
              # recréer connection ou destination space est parent
              s1 = Connection.create(space: @child)
              co = s1.children.create(space: @grand_child)
            end
            # pour chaque child de grand child, mettre à jour la co
            @grand_child.children.each do |connection|
              connection.parent_id = co.id
              connection.save
            end
            # suppr la co de grand child à initial space
            @grand_child.connections.each do |connection|
              if (connection.parent.nil? == false) && (connection.parent.space == @initial_space)
                connection.destroy
              end
            end
          # sinon
          else
            # destroy all connections
            @grand_child.connections.destroy_all
            # créer co grand child à child
            if !@child.shelves.empty? && @child.connections.empty? # si un space est sur une shelf, et n'est pas encore parent (i.e. n'a aucune connection)
              s1 = Connection.create(space: @child)
              s1.children.create(space: @grand_child)
            else
              @child.children.create(space: @grand_child)
            end
          end
        end
        # mettre pos 1 à grand_child, save
        @grand_child.position = 1
        @grand_child.save
        redirect_to space_path(@child)
      else
        redirect_to space_path(@parent)
      end
      if current_user != User.first
        UserNotifierMailer.inform_louis_of_new_space(@child, shelf_mother_of_space(@parent).user).deliver
      end
    end
  end

  def add_item_to(space)
    @item = Item.find(params[:space][:item_id])
    item_position = @item.position
    if @item.shelves.empty? == false
      @shelf.items.where('position > ?', item_position).update_all('position = position - 1') # every new object has position 1 by default --> pushes all other positions to the right
      @shelf.spaces.where('position > ?', item_position).update_all('position = position - 1')
      @item.shelves.destroy_all
    else
      @initial_space = @item.spaces.first
      @initial_space.items.where('position > ?', item_position).update_all('position = position - 1')
      @initial_space.children.each do |connection|
        if connection.space.position > item_position
          connection.space.position = connection.space.position - 1
          connection.space.save
        end
      end
      @item.spaces.destroy_all
    end
    @item.position = 1
    @item.save(validate: false)
    space.items << @item
  end

  # not dry!
  # if space.shelves is not empty (meaning the parent space is the root)
  # set the space to parent (connection to nil) and the new space to child

app/views/spaces/edit.html.erb
<%= form_for(@space) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

<%= link_to 'Cancel', space_path(@space) %>

app/views/spaces/new.html.erb
<!-- BEGINNING OF NAVBAR -->
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "shelf", root_path, class: "logo" %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if @shelf %>
      <%= link_to image_tag("Plus.png", width: 45).html_safe, shelf_path(@shelf), class: 'rotated' %>
    <% elsif @space %>
      <%= link_to image_tag("Plus.png", width: 45).html_safe, space_path(@parent), class: 'rotated' %>
    <% end %>
  </div>
</div>
<!-- END OF NAVBAR -->

<h1 class="question">What is the name of this new 🗄 ? </h1>

<% if @shelf %>
  <%= simple_form_for @space, html: { autocomplete: 'off' } do |f| %>
    <%= f.input :name, autofocus: true, label: false, html: {autocomplete: 'disabled'}, input_html: { class: "inp-txt" } %>
    <%= f.hidden_field :shelf_id, :value => @shelf.id %>
    <div class='buttonHolder' > <%= f.submit "Add space to shelf", class: "add-btn" %> </div>
  <% end %>
<% elsif @child %>
  <%= simple_form_for @child, html: { autocomplete: 'off' } do |f| %>
    <%= f.input :name , autofocus: true, label: false, html: {autocomplete: 'disabled'}, input_html: { class: "inp-txt" } %>
    <%= f.hidden_field :parent_id, :value => @parent.id %>
    <div class='buttonHolder' > <%= f.submit "Add space to shelf", class: "add-btn" %> </div>
  <% end %>
<% end %>


<!-- Understanding the raw HTML created by simple_form
<form class="simple_form new_restaurant" id="new_restaurant" novalidate="novalidate" action="/restaurants" accept-charset="UTF-8" method="post">
  <input type="hidden" name="authenticity_token" value="6mcCvU7ZazpIBcJTptw/8y4EucmzccFWli7tFUzX6IJEx8wq6PFC7m4rA1Jy+W4YW1hlhYhSOyhZefWtOM5ofQ==">
  <div class="form-group string optional restaurant_name">
    <label class="string optional" for="restaurant_name">Name</label>
    <input class="form-control string optional" type="text" name="restaurant[name]" id="restaurant_name">
  </div>
  <input type="submit" name="commit" value="Create Restaurant" data-disable-with="Create Restaurant">
</form>
 -->

app/views/spaces/show.html.erb
<% if @shelf_mother.id == 20 %>
<!-- NAVBAR AND OPTIONS BOX IF USER ON SANDBOX SHELF -->
  <!-- Navbar: Back, space title, options -->
  <div class="navbar" id="navshow">
    <div>
      <% if @parent %>
        <%= link_to image_tag("back.png", width: 37, class: "back").html_safe, space_path(@parent) %>
      <% else %>
        <%= link_to image_tag("back.png", width: 37, class: "back").html_safe, shelf_path(@shelf_mother.username) %>
      <% end %>
    </div>
    <h1 class="space-title"> <%= @space.name %> </h1>
    <div id="options-btn">
      <a><%= image_tag "options.png", alt: "Options", width: 37 %></a>
    </div>
  </div>
  <!-- Options box: Add, move, destroy -->
  <div class="options-ctn options-ctn-shelf-space space-options" id="options" style="display:none;">
    <div class="option-ctn">
      <a >➕</a>
      <a class="option-label" id="new-object-or-space">New...</a>
    </div>
<!--     <div class="option-ctn">
      <a>👉</a>
      <a class="option-label" id="move-to">Move</a>
    </div>
    <div class="option-ctn">
      <a>🗑</a>
      <% parent = nil %>
      <% @space.connections.each do |connection| %>
        <% if connection.parent_id.nil? == false %>
          <% parent = connection.parent.space %>
        <% end %>
      <% end %>
      <% if @space.shelves.empty? == false %>
        <%= link_to 'Delete', space_path(@space, shelf_id: @space.shelves.first.id), method: :delete, class: "option-label" %>
      <% elsif parent.nil? == false %>
        <%= link_to 'Delete', space_path(@space, parent_id: parent.id), method: :delete, class: "option-label" %>
      <% end %>
    </div> -->
    <div class="option-ctn">
      <a>🏡</a>
      <a href="https://www.shelf.so/users/sign_up" class="option-label" id="new-object-or-space">Sign up</a>
    </div>
    <div class="option-ctn">
      <a>🚪</a>
      <%= link_to 'Leave', root_path, class: "option-label", id: "leave-shelf" %>
    </div>
  </div>

<!-- NAVBAR AND OPTIONS BOX IF USER SIGNED IN AND ON THEIR OWN SPACE -->
<% elsif user_signed_in? && (@current_user == @shelf_mother.user) %>
  <!-- Navbar: Back, space title, options -->
  <div class="navbar" id="navshow">
    <%= link_to shelf_path(@shelf.username) do %>
      <div class="rounded-braun-button" title="Back">
        <div class="back-rounded-braun-button" id="back-item-show">👈</div>
      </div>
    <% end %>
    <div style="display: flex;">
      <div id="colored-space">
        <% if @space.name == "Not started" %>
          <%= image_tag "red_circle.png", width: 37, height: 37 %>
        <% elsif @space.name == "In progress" %>
          <%= image_tag "orange_circle.png", width: 37, height: 37 %>
        <% elsif @space.name == "Finished" %>
          <%= image_tag "green_circle.png", width: 37, height: 37 %>
        <% end %>
      </div>
      <h1 class="space-title"> <%= @space.name %> </h1>
    </div>
    <div id="options-btn" style="visibility:hidden">
      <a><%= image_tag "options.png", alt: "Options", width: 37 %></a>
    </div>
  </div>


<% elsif user_signed_in? && (@current_user != @shelf_mother.user) %>
<!-- NAVBAR AND OPTIONS BOX IF USER SIGNED IN AND NOT ON THEIR OWN SPACE -->
  <!-- Navbar: Back, space title, options -->
  <div class="navbar" id="navshow">
    <div>
      <% if @parent %>
        <%= link_to image_tag("back.png", width: 37, class: "back").html_safe, space_path(@parent) %>
      <% else %>
        <%= link_to image_tag("back.png", width: 37, class: "back").html_safe, shelf_path(@shelf_mother.username) %>
      <% end %>
    </div>
    <h1 class="space-title"> <%= @space.name %> </h1>
    <div id="options-btn">
      <a><%= image_tag "options.png", alt: "Options", width: 37 %></a>
    </div>
  </div>
  <!-- Options box: Back to my shelf -->
  <div class="options-ctn options-ctn-shelf-space space-options" id="options" style="display:none;">
    <div class="option-ctn">
      <a>🏠</a>
      <%= link_to 'Back to my shelf', shelf_path(@current_user.shelves.first.username), class: "option-label" %>
    </div>
  </div>

<% elsif user_signed_in? == false %>
<!-- NAVBAR AND OPTIONS BOX IF USER NOT SIGNED IN -->
  <!-- Navbar: Back, space title, login or sign up -->
  <div class="navbar" id="navshow">
    <div>
      <% if @parent %>
        <%= link_to image_tag("back.png", width: 37, class: "back").html_safe, space_path(@parent) %>
      <% else %>
        <%= link_to image_tag("back.png", width: 37, class: "back").html_safe, shelf_path(@shelf_mother.username) %>
      <% end %>
    </div>
    <h1 class="space-title"> <%= @space.name %> </h1>
    <div class="lp-login-signup-ctn">
      <%= link_to('Log in', new_user_session_path, class: 'login expand', id: 'login-lp', style: 'display:;') %>
      <%= link_to('Sign up', new_user_registration_path, class: 'lp-cta', id: 'signup-lp-btn', style: 'display:;') %>
      <%= link_to('Sign up', new_user_registration_path, class: 'login expand', id: 'signup-lp-simple', style: 'display:none') %>
    </div>
  </div>
  <!-- Options box: Not needed -->
<% end %>




<!-- MOVE TO LIST -->
  <div class="options-ctn" id="move-to-list" style="display:none;" data-type="space" data-space-id="<%= @space.id %>" data-shelf-id="<%= @shelf_mother.id %>">
    <div id="top-line">
      <%= image_tag("back.png", width: 23, height: 25, style: 'display:none;', id: 'left-arrow-img').html_safe %>
      <p class="option" id="top-element">Shelf</p>
    </div>
    <hr/>
    <ul id="children-spaces">
    <% move_space_to_space_list.each do |space| %>
      <% if space != @space %>
        <li>
          <a class="option" id="child-space-<%= space.id %>" data-space-id="<%= space.id %>">🗄 <%= truncate(space.name, length: 25) %></a>
        </li>
      <% end %>
    <% end %>
    </ul>
      <div id="button-new-space-parent">
        <%= image_tag("grey_plus.png", width: 18, height: 18, id: 'grey-plus-img').html_safe %>
        <div id="new-space-txt">New</div>
      </div>
    <%= button_to "👉 Move to shelf", { controller: "spaces", action: "move_space_to_shelf", current_space_id: @space.id }, id: 'move-to-button' %>
  <!--   <%= button_to "👉 Move to test", { controller: "spaces", action: "move_space_to_space", current_space_id: @space.id, destination_space_id: 1 }, id: 'move-to-button' %>
   -->
  </div>
<!-- END OF MOVE TO LIST -->

<!-- ADD OPTIONS -->
    <div class="options-ctn options-ctn-shelf-space" id="add-options" style="display:none;">
      <div class="option add-option" id="new-object">
      <% if policy(Item).create? %>
        <a>📚 New object</a>
      <% end %>
      </div>
      <div class="option add-option" id="button-new-space-child">
      <% if policy(Space).create? %>
        <a>🗄 New space</a>
      <% end %>
      </div>
    </div>
<!-- END OF ADD OPTIONS -->

<!-- ADD URL BOX -->
    <div class="options-ctn options-ctn-shelf-space" id="add-url" style="display:none;">
      <p class="option prompt" id="add-url-prompt"> Copy and paste the URL 🌐 for this new object </p>
      <%= form_for @item, remote: true do |f| %>
        <%= f.text_field :url, class: 'txt-inpt txt-inpt-box' %> <!-- autofocus: true, onblur: 'this.focus()' -->
        <%= f.hidden_field :space_id, :value => @space.id %> <!-- for controller -->
        <%= f.hidden_field :parent_id, :value => @space.id %> <!-- for pundit -->
        <%= f.submit "Add item", style: "display: none;" %>
      <% end %>
    </div>
<!-- END OF ADD URL BOX -->

<!-- ADD SPACE BOX -->
    <div class="options-ctn options-ctn-shelf-space" id="add-space" data-location="space" style="display:none;">
      <p class="option prompt" id="add-space-prompt" > What is the name of this new space? 🗄 </p>
      <%= simple_form_for @child, html: { autocomplete: 'off' } do |f| %>
        <%= f.text_field :name, class: 'txt-inpt txt-inpt-box' %>
        <%= f.hidden_field :shelf_id, :value => @shelf_mother.id %>
        <%= f.hidden_field :space_id, :value => @space.id %>
        <%= f.submit "Add space", style: "display: none;" %>
      <% end %>
    </div>
<!-- END OF ADD SPACE BOX -->

<!-- CONNECT OPTIONS -->
    <div class="options-ctn options-ctn-shelf-space" id="connect-options" style="display:none;">
      <div class="option-ctn" id="new-object">
        <a>💻</a>
        <a href="https://chrome.google.com/webstore/detail/shelf/dbnfpkfeedjlicclaffhoglpmgpdjblk?hl=en"  target="_blank" rel="noopener noreferrer" class="option-label">Chrome extension</a>
      </div>
      <% if @user %>
        <% if @user.telegram_chat_id.nil? %>
          <div class="option-ctn" id="button-new-space-child">
            <a>📱</a>
            <%= link_to 'Telegram Bot', meet_bot_path(@current_user), class: "option-label" %>
          </div>
        <% end %>
      <% end %>
    </div>
<!-- END OF CONNECT OPTIONS -->

<!-- IF SPACE IS EMPTY -->
<% if @space.children.empty? && @space.items.empty? %>
  <div class="center"><p class="msg">This space is empty.</p></div>
<% end %>
<div>
  <% if @shelf_mother.id == 20 %> <!-- the if and elsif conditions are litterally the same - could be refactored but kept as is for lisibiliy -->
    <div class="grid-container" data-controller="drag" data-drag-url="/:type/:id/move">
  <% elsif @current_user == @shelf_mother.user %>
    <div class="grid-container" data-controller="drag" data-drag-url="/:type/:id/move">
  <% else %>
    <div class="grid-container">
  <% end %>
    <% objects = @space.children.map { |connection| connection.space } + @space.items %> <!-- syntax à verif -->
    <% objects.sort_by(&:position).each do |object| %>
      <% if object.class.name == "Space" %>
        <% if policy(object).show? %>
          <div class="object" data-type="spaces" data-id="<%= object.id %>">
            <%= link_to image_tag("space.png", class: 'object-picture'), space_path(object) %>
  <!--           <%= link_to truncate(object.position.to_s + ' ' + object.name, length: 45), space_path(object),  class: "object_name" %> -->
            <%= link_to truncate(object.name, length: 45), space_path(object),  class: "object_name" %>
          </div>
        <% end %>
      <% elsif object.class.name == "Item" %>
        <% if policy(object).show? %>
          <div class="object" data-type="items" data-id="<%= object.id %>">
            <% if object.medium == "book" %>
              <%= link_to image_tag("book.png", class: 'object-picture'), item_path(object, origin: "space", space_id: @space.id) %>
            <% elsif object.medium == "podcast" %>
              <%= link_to image_tag("podcast.png", class: 'object-picture'), item_path(object, origin: "space", space_id: @space.id) %>
            <% elsif object.medium == "video" %>
              <%= link_to image_tag("video.png", class: 'object-picture'), item_path(object, origin: "space", space_id: @space.id) %>
            <% elsif object.medium == "blogpost" %>
              <%= link_to image_tag("blogpost.png", class: 'object-picture'), item_path(object, origin: "space", space_id: @space.id) %>
            <% elsif object.medium == "news_article" %>
              <%= link_to image_tag("news_article.png", class: 'object-picture'), item_path(object, origin: "space", space_id: @space.id) %>
            <% elsif object.medium == "academic_article" %>
              <%= link_to image_tag("academic_article.png", class: 'object-picture'), item_path(object, origin: "space", space_id: @space.id) %>
            <% elsif object.medium == "newsletter" %>
              <%= link_to image_tag("newsletter.png", class: 'object-picture'), item_path(object, origin: "space", space_id: @space.id) %>
            <% elsif object.medium == "tweet" %>
              <%= link_to image_tag("tweet.png", class: 'object-picture'), item_path(object, origin: "space", space_id: @space.id) %>
            <% elsif object.medium == "thread" %>
              <%= link_to image_tag("thread.png", class: 'object-picture'), item_path(object, origin: "space", shelf_id: @shelf.id) %>
            <% elsif object.medium == "audio_book" %>
              <%= link_to image_tag("audio_book.png", class: 'object-picture'), item_path(object, origin: "space", space_id: @space.id) %>
            <% elsif object.medium == "e_book" %>
              <%= link_to image_tag("e_book.png", class: 'object-picture'), item_path(object, origin: "space", space_id: @space.id) %>
            <% elsif object.medium == "online_course" %>
              <%= link_to image_tag("online_course.png", class: 'object-picture'), item_path(object, origin: "space", space_id: @space.id) %>
            <% elsif object.medium == "code_repository" %>
              <%= link_to image_tag("code_repository.png", class: 'object-picture'), item_path(object, origin: "space", space_id: @space.id) %>
            <% elsif object.medium == "blog" %>
              <%= link_to image_tag("blog.png", class: 'object-picture'), item_path(object, origin: "space", space_id: @space.id) %>
            <% else %>
              <%= link_to image_tag("blogpost.png", class: 'object-picture'), item_path(object, origin: "space", space_id: @space.id) %>
            <% end %>
  <!--           <%= link_to truncate(object.position.to_s + ' ' + object.name, length: 45), item_path(object, origin: "space", space_id: @space.id), class: "object_name" %> -->
              <%= link_to truncate(object.name, length: 40), item_path(object, origin: "space", space_id: @space.id), class: "object_name" %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>