config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users, controllers: {sessions: "sessions", registrations: "custom_registrations"}
  root to: 'pages#home'
  get "/ref=producthunt" => "pages#home"
  get "/payment" => "pages#payment", as: 'payment'
  post "/create-checkout-session" => "payments#redirect_stripe"
  # post '/hooks/stripe' => 'payments#receive'
  post '/webhook_events/:source', to: 'webhook_events#create'
  devise_scope :user do
    get "meet_bot", to: "telegram_set_up#meet_bot"
    get "shake_hands", to: "telegram_set_up#shake_hands"
    get "add_first_resource", to: "telegram_set_up#add_first_resource"
    get "/telegram_set_up/stat_telegram_chat_id", to: "telegram_set_up#stat_telegram_chat_id"
    get "/telegram_set_up/stat_added_first_item", to: "telegram_set_up#stat_added_first_item"
    get "/telegram_set_up/current_shelf", to: "telegram_set_up#current_shelf"
    get "sessions/extension", to: "sessions#new_ext"
    post "sessions/extension", to: "sessions#create_ext"
    get "/sessions/start_extension", to: "sessions#start_extension"
  end
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :items, only: [ :index, :create ]
    end
  end
  resources :telegram_set_up, only: [:new, :create] do
    collection do
      get 'stat_telegram_chat_id'
      get 'stat_added_first_item'
      get 'current_shelf'
    end
  end
  resources :shelves, only: [:new, :create, :show], param: :username do
    member do
      get 'shelf_children'
    end
  end
  resources :spaces do
    collection do
      post :move_space_to_space
      post :move_space_to_shelf
    end
    member do
      patch :move
      get 'space_name'
      get 'space_children'
    end
  end
  resources :items do
    collection do
      post :move_to_space
      post :move_to_shelf
      post :persist_mp3_url
      post :persist_audio_timestamp
      post :persist_audio_duration
      post :mark_as_finished
      get 'item_audio_duration'
      get 'was_item_added'
    end
    member do
      patch :move
    end
  end
  post '/application/update_balance_temp', to: 'application#update_balance_temp'
  post '/application/update_balance_final', to: 'application#update_balance_final'
  post '/application/pay_back_balance', to: 'application#pay_back_balance'
  get '/application/user_balance', to: 'application#user_balance'
end

app/controllers/telegram_set_up_controller.rb
class TelegramSetUpController < Devise::RegistrationsController
# skip_after_action :verify_authorized, only: [:stat_telegram_chat_id]

  def stat_telegram_chat_id
    if current_user
      @user = current_user
      render json: {is_nil: @user.telegram_chat_id.nil?}
    end
  end

  def stat_added_first_item
    if current_user
      @user = current_user
      render json: {shelf_empty: @user.shelves.first.spaces.first.items.empty?}
    end
  end

  def current_shelf
    if current_user
      @user = current_user
      render json: {shelf_id: @user.shelves.first.id}
    end
  end

  def meet_bot
  end

  def shake_hands
    if current_user
      @user = current_user
      message_new_user = "Welcome to Shelf #{@user.first_name}!
    Please open the link below to open your first conversation with Shelf Bot in Telegram.
    Once in Telegram, simply hit 'Start'.
      https://t.me/Shelf_bot?start=#{@user.telegram_hash}
    N.B. If you don't have the Telegram app installed, please do install it in order to join Shelf!"

      TwilioClient.new.send_text(@user.phone_number, message_new_user)

      UserNotifierMailer.set_up_telegram(@user).deliver
    end
  end

  def add_first_resource
    if current_user
      @user = current_user
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :phone_number, :email, :password, :password_confirmation)
  end
end

app/views/telegram_set_up/add_first_resource.html.erb
<div class="navbar" id="navshow">
    <%= link_to('shelf', root_path, class: 'logo') %>
</div>

<div class="meet-shelf-bot-ctn"> <!-- sign-up ctn refact -->
  <h2 class="meet-shelf-bot" id="add-first-resource">Now, let's send a resource to the Bot! 📚</h2>
  <p class="benefit-dsc">Now that Shelf Bot knows who you are, find a resource you like from your phone (a podcast, news article, video...) and hit Share > Telegram > Shelf.</p>
  <%= video_tag "testexport.mp4", autoplay: true, loop: true, muted: 'muted', playsinline: true, class: 'share-telegram' %>
  <%= link_to 'Done', shelf_path(@user.shelves.first.username), class: "sign-up-cta"%>
</div>

app/views/telegram_set_up/meet_bot.html.erb
<div class="navbar" id="navshow">
    <%= link_to('shelf', root_path, class: 'logo') %>
</div>

<div class="meet-shelf-bot-ctn">
  <h2 class="meet-shelf-bot">Meet Shelf Bot 🤖</h2>
  <p class="benefit-dsc">Shelf Bot 🤖 lets you add resources from mobile by hitting Share > Telegram > Shelf.</p>
  <%= video_tag "testexport.mp4", autoplay: true, loop: true, muted: true, playsinline: true, class: 'share-telegram' %>
  <%= link_to 'Get started', shake_hands_path, class: "sign-up-cta"%>
</div>

app/views/telegram_set_up/shake_hands.html.erb
<div class="navbar" id="navshow">
    <%= link_to('shelf', root_path, class: 'logo') %>
</div>

<div class="meet-shelf-bot-ctn"> <!-- sign-up ctn refact -->
  <h2 class="meet-shelf-bot" id="shake-hands">Shake hands 🤝🤖</h2>
  <p class="benefit-dsc">Open the link you received via SMS, and once in the Telegram mobile app, hit “Start”.</p>
  <%= video_tag "shake_hands.mp4", autoplay: true, loop: true, muted: true, playsinline: true, class: 'share-telegram' %>
  <p class="bottom-note"> Didn't receive our SMS? Check your e-mail! </p>
</div>