config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users, controllers: {sessions: "sessions", registrations: "custom_registrations"}
  root to: 'pages#home'
  get "/ref=producthunt" => "pages#home"
  get "/payment" => "pages#payment", as: 'payment'
  post "/create-checkout-session" => "payments#redirect_stripe"
  # post '/hooks/stripe' => 'payments#receive'
  post '/webhook_events/:source', to: 'webhook_events#create'
  devise_scope :user do
    get "meet_bot", to: "telegram_set_up#meet_bot"
    get "shake_hands", to: "telegram_set_up#shake_hands"
    get "add_first_resource", to: "telegram_set_up#add_first_resource"
    get "/telegram_set_up/stat_telegram_chat_id", to: "telegram_set_up#stat_telegram_chat_id"
    get "/telegram_set_up/stat_added_first_item", to: "telegram_set_up#stat_added_first_item"
    get "/telegram_set_up/current_shelf", to: "telegram_set_up#current_shelf"
    get "sessions/extension", to: "sessions#new_ext"
    post "sessions/extension", to: "sessions#create_ext"
    get "/sessions/start_extension", to: "sessions#start_extension"
  end
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :items, only: [ :index, :create ]
    end
  end
  resources :telegram_set_up, only: [:new, :create] do
    collection do
      get 'stat_telegram_chat_id'
      get 'stat_added_first_item'
      get 'current_shelf'
    end
  end
  resources :shelves, only: [:new, :create, :show], param: :username do
    member do
      get 'shelf_children'
    end
  end
  resources :spaces do
    collection do
      post :move_space_to_space
      post :move_space_to_shelf
    end
    member do
      patch :move
      get 'space_name'
      get 'space_children'
    end
  end
  resources :items do
    collection do
      post :move_to_space
      post :move_to_shelf
      post :persist_mp3_url
      post :persist_audio_timestamp
      post :persist_audio_duration
      post :mark_as_finished
      get 'item_audio_duration'
      get 'was_item_added'
    end
    member do
      patch :move
    end
  end
  post '/application/update_balance_temp', to: 'application#update_balance_temp'
  post '/application/update_balance_final', to: 'application#update_balance_final'
  post '/application/pay_back_balance', to: 'application#pay_back_balance'
  get '/application/user_balance', to: 'application#user_balance'
end

app/controllers/api/v1/items_controller.rb
class Api::V1::ItemsController < Api::V1::BaseController
  def index
    @items = Item.first(10)
    render json: @items
  end

  def create
    # POST /api/v1/items # authenticated
    @item = Item.new(item_params)
    # get chrome_auth_token from headers
    chrome_auth_token = request.headers["HTTP_CHROME_AUTH_TOKEN"]
    @user = User.find_by(chrome_auth_token: chrome_auth_token)
    # authorize @item
    if @item.save
      # Add newly created item to 'Added by bot' for user
      @shelf = @user.shelves.first
      @not_started_space = @shelf.spaces.where(name: 'Not started').first
      @not_started_space.items << @item
      item_url = "https://www.shelf.so/items/#{@item.id}?space_id=#{@not_started_space.id}"
      render json: {url: item_url}
    else
      render json: {
        error: "We cannot process this URL for now",
        status: 400
      }, status: 400
    end
  end

  private

  def item_params
    params.require(:item).permit(:url)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
skip_before_action :authenticate_user!, :only => [:show, :create, :destroy, :move_to_shelf, :move_to_space, :update, :item_audio_duration, :was_item_added]
before_action :set_item, only: [:show, :edit, :update, :destroy, :move, :persist_mp3_url, :persist_audio_timestamp, :persist_audio_duration, :mark_as_finished]
before_action :set_shelf, only: [:show, :move_to_shelf]
before_action :set_shelf_space, only: [:new, :show, :edit, :move]
skip_before_action :verify_authenticity_token
skip_after_action :verify_authorized, only: [:item_audio_duration, :was_item_added]

  def new
    @item = Item.new
    authorize @item
  end

  def create
    @item = Item.new(item_params)
    authorize @item
    if @item.valid?
      # if params[:item][:shelf_id].present?
        # @shelf = Shelf.find(params[:item][:shelf_id])
        RepositioningItemsAndSpacesJob.perform_later(@shelf)
      if current_user
        @shelf = current_user.shelves.first
        @not_started_space = @shelf.spaces.where(name: 'Not started').first
        @not_started_space.items << @item
      end
        # format.html do
        #   redirect_to item_path(@item, shelf_id: @shelf.id)
        # end
      # elsif params[:item][:space_id].present?
      #   @space = Space.find(params[:item][:space_id])
      #   RepositioningInSpaceJob.perform_later(@space)
      #   @space.items << @item
      #   format.html do
      #     redirect_to item_path(@item, space_id: @space.id)
      #   end
      # end
      if current_user
        if current_user != User.first
          UserNotifierMailer.inform_louis_of_new_item(@item, current_user, 'app').deliver
        end
      end
    else
      format.js { render 'shelves/show_updated_view' }
      format.json { head :ok }
    end
  end

  def create_from_chrome_ext
    # parse POST request to set vars user_id and url
    # find user
    user = User.first # user = User.find(user_id)
    # create item based on url
    # add item to user's "Added by bot" space
  end

  def index
    @items = policy_scope(Item)
  end

  def show
    # @child = Space.new
    # @parent_id = Space.new
    @space = Space.new
    # @shelf_mother = shelf_mother_of_item(@item)
    if current_user
      @user = current_user
      if @item.status == "not started"
        @item.status = "in progress"
        @shelf = @user.shelves.first
        @item.spaces.destroy_all
        @in_progress_space = @shelf.spaces.where(name: 'In progress').first
        @in_progress_space.items << @item
        @item.save
        #sassurer que si user go back, redirected vers in progress
      end
    end
    if @item.shelves.empty?
      @parent_space = @item.spaces.first
      @space = @item.spaces.first
    end
    # si shelf n'a qu'un item et 0 space OU shelf a un space added by bot qui a qu'un item
    if current_user
      if (@item.text_content.nil? == false) && ((@user.shelves.first.items.size == 1) && (@user.shelves.first.spaces.size == 1) && (@user.shelves.first.spaces.first.name == "🤖 Added by Bot") && (@user.shelves.first.spaces.first.items.empty?)) || (@user.shelves.first.items.empty? && (@user.shelves.first.spaces.size == 1) && (@user.shelves.first.spaces.first.name == "🤖 Added by Bot") && (@user.shelves.first.spaces.first.items.first.id == @item.id))
        flash.now[:notice] = "Congratulations on adding your first resource 🎉 You can listen to it for free by clicking on 'Options' in the top right and '👂 Listen'.".html_safe
      end
    end
    if params.has_key?(:origin)
      @space_back_id = params[:space_id]
    end
  end

  def edit
  end

  def update
    @item.assign_attributes(item_params)
    @item.save(validate: false)
    if params[:item][:shelf_id].present?
      @shelf = Shelf.find(params[:item][:shelf_id])
      redirect_to item_path(@item, shelf_id: @shelf.id)
    elsif params[:item][:space_id].present?
      @space = Space.find(params[:item][:space_id])
      redirect_to item_path(@item, space_id: @space.id)
    else
      redirect_to item_path(@item)
    end
  end

  def destroy
    position = @item.position
    if @item.spaces.empty? == false
      @space = @item.spaces.first
      # Tous les spaces et objets sur space avec index > index obj perdent 1
      @space.items.where('position > ?', position).update_all('position = position - 1')
      @space.children.each do |connection|
        if connection.space.position > position
          connection.space.position = connection.space.position - 1
          connection.space.save
        end
      end
      @item.destroy
      redirect_to space_path(@space)
    elsif @item.shelves.empty? == false
      @shelf = @item.shelves.first
      # Tous les spaces et objets sur shelf avec index > index obj perdent 1
      @shelf.items.where('position > ?', position).update_all('position = position - 1') # every new object has position 1 by default --> pushes all other positions to the right
      @shelf.spaces.where('position > ?', position).update_all('position = position - 1')
      @item.destroy
      redirect_to shelf_path(@shelf.username)
    end
  end

  def move_to_space
    @item = Item.find(params[:item_id])
    authorize @item
    position = @item.position

    if @item.spaces.empty? == false   # si l'item est sur un space
      # -1 to all spaces or objects AFTER the item on the initial space
      @initial_space = @item.spaces.first
      @initial_space.items.where('position > ?', position).update_all('position = position - 1')
      @initial_space.children.each do |connection|
        if connection.space.position > position
          connection.space.position = connection.space.position - 1
          connection.space.save
        end
      end
      @item.spaces.destroy_all
    elsif @item.shelves.empty? == false # si l'item est sur une shelf
      # -1 to all spaces or objects AFTER the item on the shelf
      @shelf = @item.shelves.first
      @shelf.items.where('position > ?', position).update_all('position = position - 1') # every new object has position 1 by default --> pushes all other positions to the right
      @shelf.spaces.where('position > ?', position).update_all('position = position - 1')
      @item.shelves.destroy_all
    end

    @item.position = 1
    @item.save(validate: false)

    @new_space = Space.find(params[:space_id])
    @new_space.items.update_all('position = position + 1')
    @new_space.children.each do |connection|
      connection.space.position += 1
      connection.space.save
    end
    @new_space.items << @item
    # redirect_to item_path(@item, space_id: @new_space.id)
    redirect_to space_path(@new_space)
  end

  def move_to_shelf
    @item = Item.find(params[:item_id])
    authorize @item

    # -1 to all spaces or objects AFTER the item on the initial space
    position = @item.position
    @initial_space = @item.spaces.first
    @initial_space.items.where('position > ?', position).update_all('position = position - 1')
    @initial_space.children.each do |connection|
      if connection.space.position > position
        connection.space.position = connection.space.position - 1
        connection.space.save
      end
    end

    @item.position = 1
    @item.save(validate: false)

    # @space = @item.spaces.first
    # if @space.shelves.empty? == false
    #   @shelf = @space.shelves.first
    # else
    #   @shelf = recursive_parent_search(@space).shelves.first
    # end

    # incrementing the position of all other objects and spaces on the shelf by +1
    @shelf = shelf_mother_of_item(@item)
    @shelf.items.update_all('position = position + 1')
    @shelf.spaces.update_all('position = position + 1')

    @item.spaces.destroy_all
    @shelf.items << @item
    #redirect_to item_path(@item, shelf_id: @shelf.id)
    redirect_to shelf_path(@shelf.username)
  end

  def move
    @item = Item.find(params[:id].to_i)
    current_position = @item.position
    new_position = params[:position].to_i

    if @item.shelves.empty? == false
      @shelf = @item.shelves.first
      objects = @shelf.items + @shelf.spaces # array of rails objects
    elsif @item.spaces.empty? == false
      @space = @item.spaces.first
      objects = @space.items + @space.children.map { |connection| connection.space }
    end

    objects.each do |object|
      if new_position < current_position
        if (object.position < current_position) && (object.position >= new_position)
          object.position = object.position + 1
          object.save(validate: false)
        end
      elsif new_position > current_position
        if (object.position > current_position) && (object.position <= new_position)
          object.position = object.position - 1
          object.save(validate: false)
        end
      end
    end
    @item.position = new_position
    @item.save(validate: false)
  end

  def persist_mp3_url
    @item.mp3_url = params[:mp3_url]
    @item.save
    respond_to do |format|
    format.json { head :ok }
    end
  end

  def persist_audio_timestamp
    audio_timestamp = params[:audio_timestamp]
    @item.audio_timestamp = audio_timestamp
    @item.save
    respond_to do |format|
    format.json { head :ok }
    end
  end

  def persist_audio_duration
    @item.audio_duration = params[:audio_duration]
    @item.save
    respond_to do |format|
    format.json { head :ok }
    end
  end

  def item_audio_duration
    item = Item.find(params[:id])
    audio_duration = item.audio_duration
    render json: {audio_duration: audio_duration}
  end

  def mark_as_finished
    @item.status = "finished"
    @item.spaces.destroy_all
    if current_user
      @user = current_user
      @shelf = @user.shelves.first
      @finished_space = @shelf.spaces.where(name: 'Finished').first
      @finished_space.items << @item
      @item.save
    end
    respond_to do |format|
    format.json { head :ok }
    end
  end

  def was_item_added
    if current_user
      @user = current_user
      @shelf = current_user.shelves.first

app/views/items/create.js.erb
// var element = document.querySelector("#new_item");
// var addUrlPrompt = document.querySelector("#add-url-prompt");
// element.addEventListener("ajax:error", () => {
//         addUrlPrompt.innerHTML = "err!";
// });


// window.addEventListener("load", () => {
// });

app/views/items/edit.html.erb
<% if @shelf %>
  <%= simple_form_for (@item) do |f| %>
    <%= f.label :url %>
    <%= f.text_field :url %>
    <%= f.input :medium, collection: Item::MEDIUM %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.input :status, collection: Item::STATUS %>
    <%= f.input :rank, collection: Item::RANK %>
    <%= f.label :notes %>
    <%= f.text_field :notes %>
    <%= f.hidden_field :shelf_id, :value => @shelf.id %>
    <%= f.submit "Add item" %>
  <% end %>
<% elsif @space %>
  <%= simple_form_for (@item) do |f| %>
    <%= f.label :url %>
    <%= f.text_field :url %>
    <%= f.input :medium, collection: Item::MEDIUM %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.input :status, collection: Item::STATUS %>
    <%= f.input :rank, collection: Item::RANK %>
    <%= f.label :notes %>
    <%= f.text_field :notes %>
    <%= f.hidden_field :space_id, :value => @space.id %> <!-- for controller -->
    <%= f.hidden_field :parent_id, :value => @space.id %> <!-- for pundit -->
    <%= f.submit "Add item" %>
  <% end %>
<% end %>

<%= link_to 'Cancel', url_for(:back) %>

app/views/items/new.html.erb
<% if @shelf %>
  <%= simple_form_for (@item) do |f| %>
    <%= f.label :url %>
    <%= f.text_field :url %>
    <%= f.hidden_field :shelf_id, :value => @shelf.id %>
    <%= f.submit "Add item" %>
  <% end %>
<% elsif @space %>
  <%= simple_form_for (@item) do |f| %>
    <%= f.label :url %>
    <%= f.text_field :url %>
    <%= f.hidden_field :space_id, :value => @space.id %> <!-- for controller -->
    <%= f.hidden_field :parent_id, :value => @space.id %> <!-- for pundit -->
    <%= f.submit "Add item" %>
  <% end %>
<% end %>

app/views/items/show.html.erb
<% if user_signed_in? && (@current_user.username == @shelf.username) %>
<!-- NAVBAR AND OPTIONS BOX IF USER SIGNED IN AND ON THEIR OWN ITEM -->
  <!-- Navbar: Back, item emoji, options -->
  <div class="navbar" id="navshow">
    <% if @space_back_id %>
      <%= link_to space_path(Space.find(@space_back_id)) do %>
        <div class="rounded-braun-button" title="Back">
          <div class="back-rounded-braun-button" id="back-item-show">👈</div>
        </div>
      <% end %>
    <% else %>
      <%= link_to shelf_path(@shelf.username) do %>
        <div class="rounded-braun-button" title="Back">
          <div class="back-rounded-braun-button" id="back-item-show">👈</div>
        </div>
      <% end %>
    <% end %>
    <div>
      <a id="item-medium-icon">
        <% if @item.medium == "book" %>
          <%= image_tag "book.png", width: 37 %>
        <% elsif @item.medium == "academic_article" %>
          <%= image_tag "academic_article.png", width: 37 %>
        <% elsif @item.medium == "audio_book" %>
          <%= image_tag "audio_book.png", width: 37 %>
        <% elsif @item.medium == "blog" %>
          <%= image_tag "blog.png", width: 37 %>
        <% elsif @item.medium == "e_book" %>
          <%= image_tag "e_book.png", width: 37 %>
        <% elsif @item.medium == "online_course" %>
          <%= image_tag "online_course.png", width: 37 %>
        <% elsif @item.medium == "code_repository" %>
          <%= image_tag "code_repository.png", width: 37 %>
        <% else %>
          <% if @item.status == "in progress" %> <!-- works for podcast, video, blogpost, newsletter, news_article, tweet, thread -->
             <%= image_tag "#{@item.medium}_orange.png", width: 37, id: "medium-emoji", style:"display:"%>
             <%= image_tag "#{@item.medium}_green.png", width: 37, id: "medium-emoji-marked-as-finished", style:"display: none;"%>
          <% elsif @item.status == "finished" %>
            <%= image_tag "#{@item.medium}_green.png", width: 37, id: "medium-emoji"%>
          <% end %>
        <% end %>
      </a>
    </div>
    <% if (@item.audio_duration.nil? == false) || (@item.text_content.nil?) %>
      <a class="rounded-braun-button" id="listen-braun-button" title="Listen" style="visibility:hidden">
        <div class="emoji-rounded-braun-button">👂</div>
      </a>
    <% else %>
      <a class="rounded-braun-button" id="listen-braun-button" title="Listen" style="visibility:; display:;">
        <div class="emoji-rounded-braun-button">👂</div>
      </a>
    <% end %>
    <%= link_to payment_path, class: "rounded-braun-button", id:"wallet-braun-button", title: "Wallet", style: "display:none;" do %>
      <div class="emoji-rounded-braun-button" id="wallet-emoji-in-braun-btn">👝</div>
    <% end %>
  </div>

  <!-- Edit medium box -->
  <div class="media-ctn" style="display:none;" id="media-ctn">
    <%= simple_form_for(@item) do |f| %>
      <%= f.input :medium,
        legend_tag: false,
        as: :radio_buttons,
        collection: [['blog', '📑 Blog'], ['blogpost', '📄 Blogpost'], ['news_article', '📰 News article'], ['newsletter', '🗞 Newsletter'], ['academic_article', '📃 Academic article'], ['tweet', '🐦 Tweet'], ['thread', '🧵 Thread'], ['podcast', '🎙 Podcast'], ['video', '📺 Video'], ['online_course', '🎓 Online course'], ['book', '📕 Book'], ['e_book', '📙 Ebook'], ['audio_book', '🎧 Audio book'], ['code_repository', '🐱 Code repository']],
        label_method: :second,
        value_method: :first,
        item_wrapper_class: 'option-label',
        input_html: {class: 'category-selector', onchange: 'this.form.submit();'}
      %>
    <% end %>
  </div>

  <!-- Item title -->
  <div class="main-container">
    <a target="_blank" rel="noopener noreferrer" href="<%= @item.url %>">
      <h1 class="item-title" id="item-title" data-id="<%= @item.id %>" data-timestamp="<%= @item.audio_timestamp %>" data-status="<%= @item.status %>" data-medium="<%= @item.medium %>">
        <%= @item.name %>
      </h1>
    </a>
    <div style="height: 35px"></div>

    <!-- Text content -->
    <div id="text-content"><%= @item.text_content %></div>
    <!-- Audio player -->
    <% if @item.audio_duration.nil? == false %>
      <audio id="audioPlayback" controls preload="auto" title="<%= @item.name %>">
        <source id="audioSource" type="audio/mp3" src="<%= @item.mp3_url %>">
      </audio>
    <% else %>
      <audio id="audioPlayback" controls style="display:none;">
        <source id="audioSource" type="audio/mp3" src="">
      </audio>
    <% end %>
  </div>


<% elsif user_signed_in? && (@current_user.username != @shelf.username) %>
<!-- NAVBAR AND OPTIONS BOX IF USER SIGNED IN AND NOT ON THEIR OWN ITEM -->
  <!-- Navbar: Back, item emoji, options -->
  <div class="navbar" id="navshow">
    <div>
      <% if @space_back_id %>
        <%= link_to space_path(Space.find(@space_back_id)) do %>
          <div class="rounded-braun-button" title="Back">
            <div class="back-rounded-braun-button" id="back-item-show">👈</div>
          </div>
        <% end %>
      <% else %>
        <%= link_to shelf_path(@shelf.username) do %>
          <div class="rounded-braun-button" title="Back">
            <div class="back-rounded-braun-button" id="back-item-show">👈</div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div>
      <a target="_blank" rel="noopener noreferrer" href="<%= @item.url %>">
        <% if @item.medium == "book" %>
          <%= image_tag "book.png", width: 37 %>
        <% elsif @item.medium == "podcast" %>
          <%= image_tag "podcast.png", width: 37 %>
        <% elsif @item.medium == "video" %>
          <%= image_tag "video.png", width: 37 %>
        <% elsif @item.medium == "blogpost" %>
          <%= image_tag "blogpost.png", width: 37 %>
        <% elsif @item.medium == "newsletter" %>
          <%= image_tag "newsletter.png", width: 37 %>
        <% elsif @item.medium == "news_article" %>
          <%= image_tag "news_article.png", width: 37 %>
        <% elsif @item.medium == "academic_article" %>
          <%= image_tag "academic_article.png", width: 37 %>
        <% elsif @item.medium == "tweet" %>
          <%= image_tag "tweet.png", width: 37 %>
        <% elsif @item.medium == "thread" %>
          <%= image_tag "thread.png", width: 37 %>
        <% elsif @item.medium == "audio_book" %>
          <%= image_tag "audio_book.png", width: 37 %>
        <% elsif @item.medium == "blog" %>
          <%= image_tag "blog.png", width: 37 %>
        <% elsif @item.medium == "e_book" %>
          <%= image_tag "e_book.png", width: 37 %>
        <% elsif @item.medium == "online_course" %>
          <%= image_tag "online_course.png", width: 37 %>
        <% elsif @item.medium == "code_repository" %>
          <%= image_tag "code_repository.png", width: 37 %>
        <% else %>
          <%= image_tag "web.png", width: 37 %>
        <% end %>
      </a>
    </div>
    <div id="options-btn">
      <a><%= image_tag "options.png", alt: "Options", width: 37, class: 'item-options' %></a>
    </div>
  </div>
  <!-- Options box: Back to my shelf -->
  <div class="options-ctn item-options" id="options" style="display:none;">
    <div class="option-ctn">
      <a>🏠</a>
      <%= link_to 'Back to my shelf', shelf_path(@current_user.shelves.first.username), class: "option-label" %>
    </div>
  </div>
  <!-- Item title -->
  <div class="main-container">
    <a target="_blank" rel="noopener noreferrer" href="<%= @item.url %>">
      <h1 class="item-title">
        <%= @item.name %>
      </h1>
    </a>
    <!-- Text content -->
    <div style="height: 35px"></div>
    <div id="text-content"><%= @item.text_content %></div>
    <!-- Ajouter audio player -->
    <% if @item.mp3_url.nil? == false %>
      <audio id="audioPlayback" controls preload="auto" title="<%= @item.name %>">
        <source id="audioSource" type="audio/mp3" src="<%= @item.mp3_url %>">
      </audio>
    <% end %>
  </div>

<% elsif user_signed_in? == false %>
<!-- NAVBAR AND OPTIONS BOX IF USER NOT SIGNED IN -->
  <!-- Navbar: Back, item emoji, login or sign up -->
  <div class="navbar" id="navshow">
    <div>
      <%= link_to(root_path) do %>
        <div class="rounded-braun-button" title="Back">
          <div class="back-rounded-braun-button" id="back-item-show">👈</div>
        </div>
      <% end %>
    </div>


    <div>
      <a target="_blank" rel="noopener noreferrer" href="<%= @item.url %>">
        <% if @item.medium == "book" %>
          <%= image_tag "book.png", width: 37 %>
        <% elsif @item.medium == "podcast" %>
          <%= image_tag "podcast.png", width: 37 %>
        <% elsif @item.medium == "video" %>
          <%= image_tag "video.png", width: 37 %>
        <% elsif @item.medium == "blogpost" %>
          <%= image_tag "blogpost.png", width: 37 %>
        <% elsif @item.medium == "newsletter" %>
          <%= image_tag "newsletter.png", width: 37 %>
        <% elsif @item.medium == "news_article" %>
          <%= image_tag "news_article.png", width: 37 %>
        <% elsif @item.medium == "academic_article" %>
          <%= image_tag "academic_article.png", width: 37 %>
        <% elsif @item.medium == "tweet" %>
          <%= image_tag "tweet.png", width: 37 %>
        <% elsif @item.medium == "thread" %>
          <%= image_tag "thread.png", width: 37 %>
        <% elsif @item.medium == "audio_book" %>
          <%= image_tag "audio_book.png", width: 37 %>
        <% elsif @item.medium == "blog" %>
          <%= image_tag "blog.png", width: 37 %>
        <% elsif @item.medium == "e_book" %>
          <%= image_tag "e_book.png", width: 37 %>
        <% elsif @item.medium == "online_course" %>
          <%= image_tag "online_course.png", width: 37 %>
        <% elsif @item.medium == "code_repository" %>
          <%= image_tag "code_repository.png", width: 37 %>
        <% else %>
          <%= image_tag "web.png", width: 37 %>
        <% end %>
      </a>
    </div>
      <div class="lp-login-signup-ctn">
        <%= link_to('Log in', new_user_session_path, class: 'login expand', id: 'login-lp', style: 'display:;') %>
        <%= link_to('Sign up', new_user_registration_path, class: 'lp-cta', id: 'signup-lp-btn', style: 'display:;') %>
        <%= link_to('Sign up', new_user_registration_path, class: 'login expand', id: 'signup-lp-simple', style: 'display:none') %>
      </div>
  </div>
  <!-- Options box: Not needed -->
  <!-- Item title -->
  <div class="main-container">
    <a target="_blank" rel="noopener noreferrer" href="<%= @item.url %>">
      <h1 class="item-title">
        <%= @item.name %>
      </h1>
    </a>
    <!-- Text content -->
    <div style="height: 35px"></div>
    <div id="text-content"><%= @item.text_content %></div>
    <!-- Ajouter audio player -->
    <% if @item.mp3_url.nil? == false %>
      <audio id="audioPlayback" controls preload="auto" title="<%= @item.name %>">
        <source id="audioSource" type="audio/mp3" src="<%= @item.mp3_url %>">
      </audio>
    <% end %>
  </div>
<% end %>